title: Nathalia Andrea Portilla Rincon
description: I am a microbiologist, bioinformatician, and phage/biotech lover
theme: cayman
social:
  github: https://github.com/portillanath
  twitter: https://twitter.com/portillanath
  linkedin: https://linkedin.com/in/nathaliaportilla

url: https://username.github.io 
